---
- hosts: workstation_arch
  # Run with sudo, root
  become: true

  # Load default variables
  vars_files:
    - host-vars/arch-config.yml

  # Load override
  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
    - name: Include overlay configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ dotfiles_overlay_dir }}/config-arch.yml"
      tags: ['always']

  tasks:
    - name: Set up Linux desktop
      import_tasks: tasks/linux.yml
      tags: ['workstation-arch']
