# Assume following are installed by system tasks for Emacs:
# - Fonts
# - ripgrep, aspell, pandoc

- name: "Check if ~/.config/emacs exists"
  ansible.builtin.stat:
    path: "~/.config/emacs"
  register: emacs_dir
  tags: [ "dotfiles", "emacs" ]
  become: true
  become_user: "{{ target_user }}"

# Clone the Doom Emacs framework into ~/.config/emacs if it doesn't exist
# per https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#doom-emacs
- name: "Install Doom Emacs"
  ansible.builtin.git:
    repo: https://github.com/doomemacs/doomemacs.git
    dest: ~/.config/emacs
    version: master
    force: yes
  tags: [ "dotfiles", "emacs" ]
  become: true
  become_user: "{{ target_user }}"
  when: emacs_dir.stat.exists == False

# Sync Doom Emacs packages
- name: "Sync Doom Emacs packages"
  ansible.builtin.command: "~/.config/emacs/bin/doom sync"
  tags: [ "dotfiles", "emacs" ]
  become: true
  become_user: "{{ target_user }}"
