---
- name: Set up snap packages
  import_tasks: tasks/snap.yml
  tags: ['workstation-ubuntu', 'snap', 'package', 'laptop-ubuntu']
  when: ansible_distribution == "Ubuntu"

- name: Set up apt packages
  import_tasks: tasks/ubuntu/apt.yml
  tags: ['workstation-ubuntu', 'apt', 'package', 'laptop-ubuntu']
  when: ansible_distribution == "Ubuntu"

- name: Set up deb-get packages
  import_tasks: tasks/ubuntu/deb-get.yml
  tags: ['workstation-ubuntu', 'deb-get', 'package', 'laptop-ubuntu']
  when: ansible_distribution == "Ubuntu"

- name: Set up pacman packages
  import_tasks: tasks/arch/pacman.yml
  tags: ['workstation-arch', 'pacman', 'package']
  when: ansible_distribution == "Archlinux"

- name: Set up dnf packages
  import_tasks: tasks/fedora/dnf.yml
  tags: ['workstation-fedora', 'dnf', 'package']
  when: ansible_distribution == "Fedora"

- name: Set up nix packages
  import_tasks: tasks/nix.yml
  tags: ['workstation-ubuntu', 'nix', 'package', 'laptop-ubuntu', 'workstation-fedora']

- name: Set up pip packages
  import_tasks: tasks/pip.yml
  tags: ['workstation-ubuntu', 'pip', 'package', 'laptop-ubuntu', 'workstation-fedora', 'workstation-arch']

- name: Set up flatpaks
  import_tasks: tasks/flatpak.yml
  tags: ['workstation-ubuntu', 'flatpak', 'package', 'workstation-fedora']

- name: Set up Rust packages
  import_tasks: tasks/rust.yml
  tags: ['workstation-ubuntu', 'rust', 'package', 'laptop-ubuntu', 'workstation-fedora']

- name: Set up DevOps packages
  import_tasks: tasks/ubuntu/devops-b.yml
  tags: ['workstation-ubuntu', 'devops-b', 'laptop-ubuntu']
  when: configure_devops_b and ansible_distribution == "Ubuntu"

- name: Set up extra optional packages
  import_tasks: tasks/ubuntu/extras.yml
  tags: ['workstation-ubuntu', 'extras', 'laptop-ubuntu']
  when: configure_extras and ansible_distribution == "Ubuntu"

- name: Configure Gnome settings
  import_tasks: tasks/gnome.yml
  tags: ['workstation-ubuntu', 'gnome', 'desktop', 'workstation-fedora']
  when: configure_gnome

- name: Set up Gnome dnf packages
  import_tasks: tasks/fedora/dnf-gnome.yml
  tags: ["workstation-fedora", "dnf-gnome", "package", 'workstation-fedora']
  when: configure_gnome and ansible_distribution == "Fedora"

- name: Set up other Fedora settings
  import_tasks: tasks/fedora/other.yml
  tags: ["workstation-fedora", "other"]
  when: ansible_distribution == "Fedora"

- name: Synchronize git repositories
  import_tasks: tasks/repos.yml
  tags: ['workstation-ubuntu', 'laptop-ubuntu', 'repos', 'workstation-fedora']
  when: configure_repos

- name: Set up Emacs
  import_tasks: tasks/emacs.yml
  tags: ['workstation-ubuntu', 'laptop-ubuntu', 'emacs', 'workstation-fedora', 'workstation-arch']
  when: configure_emacs

- name: Set up and synchronize dotfiles
  import_tasks: tasks/dotfiles.yml
  when: configure_dotfiles
  tags: ['workstation-ubuntu', 'workstation-fedora', 'laptop-ubuntu', 'dotfiles', 'workstation-arch']

- name: Set up fonts
  import_tasks: tasks/fonts.yml
  when: configure_dotfiles
  tags: ['workstation-ubuntu', 'workstation-fedora', 'laptop-ubuntu', 'fonts']

- name: Set up Node
  import_tasks: tasks/node.yml
  tags: ['workstation-ubuntu', 'laptop-ubuntu', 'node', 'workstation-fedora']
  when: configure_emacs

# Use distribution package managers instead
#    - import_tasks: tasks/haskell.yml
#      tags: ['workstation-ubuntu', 'laptop-ubuntu', 'haskell']

#    - block:
#        - name: Run configured post-provision ansible task files.
#          include_tasks: "{{ outer_item }}"
#          loop_control:
#            loop_var: outer_item
#          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
#      tags: ['post']
