# Nix - Check with if Nix command is installed
- name: Nix - Check if Nix is installed
  ansible.builtin.stat:
    path: /home/{{ target_user }}/.nix-profile/bin/nix
  register: nix_installed
  tags: ['workstation-ubuntu', 'nix', 'package', 'laptop-ubuntu', 'workstation-arch']
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Archlinux" or ansible_distribution == "Fedora"

- name: Nix - Check if Nix is installed
  ansible.builtin.stat:
    path: /nix
  register: nix_installed
  tags: ['nix', 'package', 'workstation-macos']  
  when: ansible_distribution == "Darwin"

# Update Nix
- name: Nix - Update Nix
  ansible.builtin.command: "nix-channel --update"
  become: true
  become_user: "{{ target_user }}"
  tags: ['workstation-ubuntu', 'nix', 'package', 'laptop-ubuntu', 'workstation-arch', 'workstation-macos']
  when: nix_installed.stat.exists

# Upgrade all Nix packages
- name: Nix - Upgrade all Nix packages
  ansible.builtin.command: "nix-env -u"
  become: true
  become_user: "{{ target_user }}"
  tags: ['workstation-ubuntu', 'nix', 'package', 'laptop-ubuntu', 'workstation-arch', 'workstation-macos']
  when: nix_installed.stat.exists

# Install Nix packages defined in installed_nix_packages
- name: Nix - Install Nix packages
  ansible.builtin.command: "nix-env -iA {{ item }}"
  become: true
  become_user: "{{ target_user }}"
  loop: "{{ nix_installed_packages }}"
  tags: ['workstation-ubuntu', 'nix', 'package', 'laptop-ubuntu', 'workstation-arch', 'workstation-macos']
  register: nixenvia_result
  changed_when: "'copying' in nixenvia_result.stdout"
  failed_when: "'error' in nixenvia_result.stdout"
  when: nix_installed.stat.exists

# Garbage collect old generations
- name: Nix - Garbage collect generations older than 30 days
  ansible.builtin.command: "nix-collect-garbage --delete-older-than 30d"
  become: true
  become_user: "{{ target_user }}"
  tags: ['workstation-ubuntu', 'nix', 'package', 'laptop-ubuntu', 'workstation-arch', 'workstation-macos']
  when: nix_installed.stat.exists
