- name: "Check if lazyvim directory exists"
  ansible.builtin.stat:
    path: "~/.config/nvim-lazyvim"
  register: lazyvim_dir
  tags: ["dotfiles", "nvim"]
  become: true
  become_user: "{{ target_user }}"

# Clone the Lazyvim Neovim framework if it doesn't exist
# per http://www.lazyvim.org/installation
- name: "Install LazyVim Neovim Setup"
  ansible.builtin.git:
    repo: https://github.com/LazyVim/starter
    dest: ~/.config/nvim-lazyvim
    version: main
    force: yes
  tags: ["dotfiles", "nvim"]
  become: true
  become_user: "{{ target_user }}"
  when: lazyvim_dir.stat.exists == False
