# Refresh and Upgrade all packages installed by pipx for user
- name: pipx - Installa and Upgrade all packages
  community.general.pipx:
    name:
      - tldr
      # For Emacs Python
      - python-lsp-server
      # python package required for ansible community.general.dconf
      - psutil
    state: latest
  tags: ['workstation-ubuntu', 'laptop-ubuntu', 'pip', 'pipx', 'package', 'devops-b', 'workstation-arch', 'python']
  become: true
  become_user: "{{ target_user }}"

# Refresh and Upgrade all packages installed by pipx for user
- name: pipx - Installa and Upgrade all packages and include applications of dependent packages
  community.general.pipx:
    name:
      - ansible
    state: latest
    install_deps: true
  tags: ['workstation-ubuntu', 'laptop-ubuntu', 'pip', 'pipx', 'package', 'devops-b', 'workstation-arch', 'python']
  become: true
  become_user: "{{ target_user }}"

# Set up conda package manager installed by Nix
# Per conda section at https://nixos.wiki/wiki/Python
# Shell configuration changes have already been made in dotfiles repo
- name: conda - Set up conda package manager from conda-shell installed by Nix
  ansible.builtin.shell: |
    conda-shell
    conda-install
  args:
    executable: /bin/bash
    chdir: "/home/{{ target_user }}"
    creates: "$HOME/.conda/bin/conda"
  become: true
  become_user: "{{ target_user }}"
  tags: ['workstation-ubuntu', 'laptop-ubuntu', 'python', 'conda', 'package']
  when: ansible_distribution == "Ubuntu"
