dotfiles_directories:
  # - "/home/{{ target_user }}/.config/xmonad"
  # - "/home/{{ target_user }}/.config/xmobar"

apt_installed_packages:
  ### Node
  #### use nvm instead
  #### - nodejs
  #### - npm
  ### Rust
  #### pkg-config required for cargo-update
  #### - pkg-config
  ### Haskell - GHCup Dependencies
  #### Install GHCup manually
  #### - build-essential
  #### - libffi-dev
  #### - libffi8ubuntu1
  #### - libgmp-dev
  #### - libgmp10
  #### - libncurses-dev
  #### - libncurses5
  #### - libtinfo5

apt_installed_packages_extras_ytdlp:
  ### Download GUI, can use aria2
  ### - uget
  ## yt-dlp
  - ffmpeg
  ## Downloaders
  ### Downloader
  - aria2

rust_installed_packages:
  - exa
  - du-dust
  - procs
  - bottom
  - zoxide
  # - broot
  - monolith
  - topgrade
  - sd
  - cargo-update

pipx_installed_packages_extras_ytdlp:
  ## yt-dlp
  - yt-dlp
  ### yt-dlp - Other Possible Dependencies
  #### Audio metadata
  - mutagen
  #### File extended attributes on Linux, MacOS
  - xattr

# Packages not present in pipx
pip_installed_packages_extras_ytdlp:
  ## yt-dlp
  ### Recommended - Certificates - Mozilla root certificate bundle
  - certifi
  ### Recommended - Encoding
  - brotli
  #### Downloads over websocket
  - websockets
  #### AES-128 and similar streams
  - pycryptodomex

nix_installed_packages:
  # Shell
  - nixpkgs.fish
  - nixpkgs.nushell
  - nixpkgs.starship
  - nixpkgs.bat
  # Fonts
  - nixpkgs.iosevka
  - nixpkgs.source-code-pro
  # Even though installed by apt, require for program like exa
  - nixpkgs.fira-code
  # Email
  # movd to home-manager
  # - nixpkgs.thunderbird
  # File Management
  - nixpkgs.lf
  - nixpkgs.gitui
  - nixpkgs.img2pdf
  - nixpkgs.duf
  - nixpkgs.bottom
  - nixpkgs.kondo
  - nixpkgs.broot
  # Terminal
  - nixpkgs.tmux
  - nixpkgs.mprocs
  - nixpkgs.dogdns
  ## Lower Priority
  ## - nixpkgs.bottom
  ## - nixpkgs.sd
  ## Former rust cargo installs
  - nixpkgs.du-dust
  ### Remove unmaintained - nixpkgs.exa, replaced by eza
  - nixpkgs.eza
  - nixpkgs.monolith
  - nixpkgs.procs
  - nixpkgs.topgrade
  - nixpkgs.zoxide
  # DevOps
  - nixpkgs.neovim
  ## PlantUML
  - nixpkgs.plantuml
  ## Document conversion, Emacs exports
  - nixpkgs.pandoc
  ## Python
  - nixpkgs.conda
