# Variables for playbooks

# Whether to set up certain software, configurations
configure_dotfiles: true
configure_emacs: true
configure_devops_b: true
configure_extras: true
configure_repos: true
configure_mpv: true
configure_gnome: true
configure_dolphin: true
configure_todoandcht: true

downloads: ~/.ansible-downloads/

# Location of this repository
dotfiles_repo: "git@github.com:justunsix/dotfiles.git"
dotfiles_repo_version: "main"
dotfiles_repo_accept_hostkey: false
dotfiles_repo_local_destination: "~/Code/dotfiles"

dotfiles_home: "~"

dotfiles_directories:
  - "/home/{{ target_user }}/usr/bin"
  - "/home/{{ target_user }}/Templates"
  - "/home/{{ target_user }}/.config/fish"
  - "/home/{{ target_user }}/.config/hunspell"
  - "/home/{{ target_user }}/.local/share/applications"
  - "/home/{{ target_user }}/.config/broot"
  - "/home/{{ target_user }}/.config/cool-retro-term"
  - "/home/{{ target_user }}/.config/i3"
  - "/home/{{ target_user }}/.config/i3status"
  - "/home/{{ target_user }}/.config/nushell"
  - "/home/{{ target_user }}/.config/helix"
  - "/home/{{ target_user }}/.config/home-manager"
  - "/home/{{ target_user }}/.config/navi"
  - "/home/{{ target_user }}/.config/nvim"
  - "/home/{{ target_user }}/.config/nvim/lua/custom/plugins"
  - "/home/{{ target_user }}/.config/rofi"
  - "/home/{{ target_user }}/.config/copyq"
  - "/home/{{ target_user }}/.config/doom"
  - "/home/{{ target_user }}/.config/doom/modules/jt/minimal"
  - "/home/{{ target_user }}/.config/doom/modules/jt/music"
  - "/home/{{ target_user }}/.config/doom/modules/jt/doomconfig"
  - "/home/{{ target_user }}/.config/doom/modules/jt/hyperbole"  
  - "/home/{{ target_user }}/.config/dunst"
  - "/home/{{ target_user }}/.config/lazyvim"
  - "/home/{{ target_user }}/.config/lazyvim/lua/plugins"
  - "/home/{{ target_user }}/.config/lazyvim/lua/config"
  - "/home/{{ target_user }}/.config/mpv/scripts"
  - "/home/{{ target_user }}/.config/mpv/script-opts"
  - "/home/{{ target_user }}/.config/mprocs"
  - "/home/{{ target_user }}/.config/todotxt-cli"
  - "/home/{{ target_user }}/.config/todotxt-cli/.todo.actions.d"
  - "/home/{{ target_user }}/.config/topgrade"
  - "/home/{{ target_user }}/.config/fontconfig/conf.d"
  - "/home/{{ target_user }}/.config/tmux"
  - "/home/{{ target_user }}/.config/wezterm"
  - "/home/{{ target_user }}/.config/vlc"

dotfiles_files:
  - .bashrc
  - .bash_aliases
  - .bash_profile
  - .gitconfig
  - .inputrc
  - Templates/New-Text-Document.txt
  - .local/share/applications/firefox-profile-manager-flatpak.desktop
  - .local/share/applications/vlc-playlist.desktop
  - .local/share/applications/clipboard-html-to-org.desktop
  - .local/share/applications/screenshot-ocr.desktop
  # - .local/share/applications/emacs-doom.desktop
  - usr/bin/jt-gc.sh
  - usr/bin/jt-gs.sh
  - usr/bin/jt-gt.sh
  - usr/bin/jt-update-all.sh
  - usr/bin/jt-clean-up.sh
  - usr/bin/jt-ocr-to-clipboard.sh
  - usr/bin/jt-post-i3.sh
  - usr/bin/jt-clip-html-to-org.sh
  - usr/bin/jt-uninstall-cargo-rust-and-packages.sh
  - usr/bin/common.sh
  # Manage VS Code Settings manually due to possible sensitive settings
  #  - .config/Code/User/settings.json
  - .config/broot/verbs.hjson
  - .config/cool-retro-term/cool-retro-term-my-futuristic.json
  - .config/copyq/copyq.conf
  - .config/copyq/copyq-commands.ini
  - .config/doom/config.el
  - .config/doom/init.el
  - .config/doom/packages.el
  - .config/doom/modules/jt/minimal/config.el
  - .config/doom/modules/jt/minimal/autoload.el  
  - .config/doom/modules/jt/music/autoload.el
  - .config/doom/modules/jt/music/config.el
  - .config/doom/modules/jt/music/packages.el
  - .config/doom/modules/jt/doomconfig/config.el
  - .config/doom/modules/jt/doomconfig/autoload.el
  - .config/doom/modules/jt/hyperbole/config.el
  - .config/doom/modules/jt/hyperbole/packages.el
  - .config/dunst/dunstrc
  # - .config/emacs/init.el
  # - .config/emacs/setup/extras.el
  # - .config/emacs/setup/minimal.el
  # - .config/emacs/setup/other.el
  # - .config/emacs/setup/variables.el
  # - .config/emacs/setup/jt-emacs-abbrev.el
  # - .config/emacs/setup/jt-emacs-package-managers.el
  # - .config/emacs/setup/jt-emacs-org.el
  # - .config/emacs/setup/jt-emacs-org-roam.el
  # - .config/emacs/setup/jt-emacs-org-babel-literate.el
  # - .config/emacs/setup/jt-emacs-org-srs-anki.el
  # - .config/emacs/setup/jt-emacs-org-present.el
  # - .config/emacs/setup/jt-emacs-ai.el
  # - .config/emacs/setup/jt-emacs-ui.el
  # - .config/emacs/setup/jt-emacs-languages.el
  # - .config/emacs/setup/jt-emacs-languages-python.el
  # - .config/emacs/setup/jt-emacs-languages-java.el
  # - .config/emacs/setup/jt-emacs-terminal.el
  # - .config/emacs/setup/jt-emacs-spelling.el
  # - .config/emacs/setup/jt-emacs-completion-ivy-counsel.el
  # - .config/emacs/setup/jt-emacs-dired.el
  # - .config/emacs/snippets/org-mode/filetags
  # - .config/emacs/snippets/org-mode/new-note
  # - .config/emacs/snippets/org-mode/plantuml
  - .config/fish/config.fish
  - .config/fontconfig/conf.d/10-nixpkg-fonts.conf
  - .config/helix/config.toml
  - .config/i3/config
  - .config/i3status/config
  - .config/lazyvim/lua/config/keymaps.lua
  - .config/lazyvim/lua/config/options.lua
  - .config/lazyvim/lua/config/lazy.lua
  - .config/lazyvim/lua/plugins/org-mode.lua
  - .config/lazyvim/lua/plugins/gen.lua
  - .config/lazyvim/lua/plugins/extend-neo-tree.lua
  - .config/lazyvim/lua/plugins/extend-lazyvim.lua
  - .config/mpv/input.conf
  - .config/mpv/mpv.conf
  - .config/mpv/scripts/autoload.lua
  - .config/mpv/script-opts/osc.conf
  - .config/mprocs/mprocs.yaml
  - .config/home-manager/home.nix
  - .config/navi/config.yaml
  - .config/nushell/config.nu
  - .config/nushell/env.nu
  - .config/nushell/config-nix.nu
  - .config/nvim/init.lua
  - .config/nvim/lua/custom/plugins/init.lua
  - .config/rofi/config.rasi
  - .config/todotxt-cli/todo.cfg
  - .config/todotxt-cli/todo-work.cfg
  - .config/todotxt-cli/.todo.actions.d/edit
  - .config/todotxt-cli/.todo.actions.d/pn
  - .config/topgrade/topgrade.toml
  - .config/tmux/tmux.conf
  - .config/wezterm/wezterm.lua
  - .config/vlc/vlcrc
  # Manage Dolphin file manager settings with copy due to frequently
  # window position changes from opening the program
  # - .config/dolphinrc
  - .config/kdeglobals
  - .config/starship.toml
  - .config/gfold.toml  

dotfiles_to_be_removed:
  - "/home/{{ target_user }}/.config/topgrade.toml"
  - "/home/{{ target_user }}/.emacs"
  - "/home/{{ target_user }}/.emacs.d"

dotfiles_files_binaries:
  - usr/bin/jt-gc.sh
  - usr/bin/jt-gs.sh
  - usr/bin/jt-gt.sh
  - usr/bin/jt-update-all.sh
  - usr/bin/jt-clean-up.sh
  - usr/bin/jt-ocr-to-clipboard.sh
  - usr/bin/jt-post-i3.sh
  - usr/bin/jt-clip-html-to-org.sh
  - usr/bin/jt-uninstall-cargo-rust-and-packages.sh
  - .config/todotxt-cli/.todo.actions.d/edit
  - .config/todotxt-cli/.todo.actions.d/pn
  # ensure directory is executable as a symlink
  # - .config/emacs/snippets

# Optional location of dotfile overlay to override or add to existing dotfiles in this repository
dotfiles_overlay_dir: "{{ playbook_dir }}/../dotfiles-overlay"

# User for which set up is being done for
# Override with your user name
target_user: user

# Personal Repositories to be cloned, synchronized
git_repositories:
  # Value of dotfiles_repo variable
  - "{{ dotfiles_repo }}"

# Other people's Git Repositories to be cloned, synchronized
git_repositories_external:
  - git@github.com:todotxt/todo.txt-cli.git
  - git@github.com:Zren/mpv-osc-tethys.git

git_repositories_reference:
  - git@github.com:adafruit/Adafruit_CircuitPython_MacroPad.git
  - git@github.com:daviwil/emacs-from-scratch.git
  - git@github.com:geerlingguy/mac-dev-playbook.git
  - git@github.com:zerolfx/copilot.el.git  

git_repositories_haskell:
  - git@github.com:xmonad/xmonad.git
  - git@github.com:xmonad/xmonad-contrib.git

apt_ppa_repositories:
  # - ppa:christian-boxdoerfer/fsearch-stable
  # - ppa:thopiekar/openrgb
  # - ppa:kelleyk/emacs
  # - ppa:fish-shell/release-3

apt_installed_packages:
  # System
  - input-remapper
  # X Clipboard management, integration with pyperclip
  - xsel
  # Package Management
  - aptitude
  - flatpak
  - curl
  ## Fonts, Codecs
  - ubuntu-restricted-extras
  ### Emacs
  - fonts-cantarell
  - fonts-jetbrains-mono
  ### Starship prompt nerd font
  - fonts-firacode
  ## Shell support
  ### Keep apt installed due to sourcing Debian key bindings
  - fzf
  ## Screenshot
  - flameshot
  ## File Management
  - dolphin
  - kde-cli-tools
  - qt5ct
  - adwaita-qt
  - konsole
  ### Android Phone Connectivity
  ### Requires restart to work
  - gmtp
  ## File Synchronization
  - git-all
  ## Web
  - transmission
  - transmission-remote-gtk
  ## Email
  ### Replacing with Thunderbird, in testing
  ## - evolution-ews
  ## Office
  - libreoffice
  ## Optical Character Recognition (OCR)
  - tesseract-ocr
  - tesseract-ocr-eng
  - tesseract-ocr-fra
  - tesseract-ocr-chi-sim
  - tesseract-ocr-chi-tra
  - gimagereader
  ## Key Bindings
  - input-remapper
  ## User Interface
  - gnome-shell-extension-manager
  - gnome-tweaks
  ## Security DNS
  - resolvconf
  ### Anti-virus
  - clamav
  - clamav-daemon
  #### RAR scanning support for ClamAV
  #### Remove in Ubuntu 24.04
  #### - libclamunrar9
  ## System
  - bleachbit
  ### Windows Management i3
  - i3
  - dmenu
  #### moved to nix
  #### - rofi
  - lxappearance
  - copyq
  ### System - Language
  - language-pack-gnome-en
  - language-pack-gnome-fr
  ## Media, Sound, Video
  - pavucontrol
  ## DevOps Editors
  - vim
  ### Emacs
  # - emacs28-nativecomp
  - hunspell
  - hunspell-en-gb
  - hunspell-fr
  #### Shellcheck used by Emacs Flymake for shell scripts by default - Emacs 29.1
  - shellcheck
  ## DevOps Languages
  - python3
  - python3-pip
  - pipx
  - python3-virtualenv
  ## DevOps Support
  ### Python package required for ansible community.general.dconf
  - python3-psutil
  ### Virtualization
  - virtualbox
  #### Latex
  - texlive-latex-base
  - texlive-latex-extra
  ## Media
  - mpv

apt_installed_packages_devops:
  # - docker
  # - docker-compose

pipx_installed_packages:
  - ansible
  - tldr
  # For Emacs, Helix Python - pylsp
  - python-lsp-server

nix_installed_packages_ytdlp:
  # yt-dlp
  - nixpkgs.yt-dlp
  - nixpkgs.ffmpeg_5-full
  ## Downloader - aria2c
  - nixpkgs.aria
  ## Meta data
  - nixpkgs.atomicparsley
  # yt-dlp python packages
  - nixpkgs.python311Packages.mutagen
  - nixpkgs.python310Packages.xattr
  - nixpkgs.python311Packages.certifi
  - nixpkgs.python311Packages.brotli
  - nixpkgs.python311Packages.websockets
  - nixpkgs.python311Packages.pycryptodome

deb_get_installed_packages:
  ## Security
  ## - nordvpn

nix_installed_packages_devops:
  - nixpkgs.minikube
  - nixpkgs.terraform
  - nixpkgs.kubectl
  - nixpkgs.jdk
  - nixpkgs.maven
  - nixpkgs.gradle

apt_removed_packages:
  - emacs-common
  - emacs
  - thunderbird
  - evolution

snap_installed_packages:
  # Web
  ## - firefox - use flatpak only
  # Media, Sound, Video
  - vlc

snap_installed_packages_classic:
  # Devops
  ## Editors
  - code
  - pycharm-community  
  ## - emacs

snap_installed_packages_devops:
  # - pycharm-community

flatpak_installed_packages:
  # Web
  - org.mozilla.firefox
  - com.github.tchx84.Flatseal
  - com.microsoft.Edge
  - io.github.ungoogled_software.ungoogled_chromium
  ## Email
  - org.mozilla.Thunderbird
  ## RSS
  - me.hyliu.fluentreader
  ## Video
  - io.freetubeapp.FreeTube
  # Learning
  ## Books
  - com.calibre_ebook.calibre
  ## SRS - Anki
  - net.ankiweb.Anki
  ## Games
  ### - net.lutris.Lutris
  # Media
  ## Bino (3d, VR player) (Optional)
  ## - org.bino3d.bino
  # Productivity - Windows Programs
  - com.usebottles.bottles
  ## Graphics
  - org.inkscape.Inkscape
  - org.gimp.GIMP
  - org.kde.krita
  ## Terminal Emulator
  - org.wezfurlong.wezterm
  # Office, Diagramming
  - com.jgraph.drawio.desktop
  # Files
  ## Peazip will use KDE modules and get them
  - io.github.peazip.PeaZip
  - io.github.cboxdoerfer.FSearch
  # Security
  - org.keepassxc.KeePassXC
