- name: scoop - Add the extras, java buckets
  community.windows.win_scoop_bucket:
    name: "{{ item }}"
    state: present
  loop:
    - extras
    - java
- name: scoop - Install packages
  community.windows.win_scoop:
    name: "{{ item }}"
    state: present
  loop: "{{ scoop_installed_packages }}"
  tags: ['scoop', 'workstation-windows', 'package']

- name: scoop - Initialize conda scoop package for PowerShell
  ansible.windows.win_powershell:
    script: |
      conda init powershell
  tags: ['scoop', 'workstation-windows', 'package', 'conda']
