- name: scoop - Add additional buckets
  community.windows.win_scoop_bucket:
    name: "{{ item }}"
    state: present
  loop:
    - extras
    - java
    - nerd-fonts
- name: scoop - Install packages
  community.windows.win_scoop:
    # Separate packages with a space from yaml list
    name: "{{ scoop_installed_packages | join(' ') }}"
    state: present
  tags: ['scoop', 'workstation-windows', 'package']

- name: scoop - Initialize conda scoop package for PowerShell
  ansible.windows.win_powershell:
    script: |
      conda init powershell
  tags: ['scoop', 'workstation-windows', 'package', 'conda']
