# From https://gist.github.com/zeitounator/fe7bca472f1cb649d91b6bc3794626a9 and
# https://stackoverflow.com/questions/67951832/ansible-importing-gpg-keys-from-rpm-fusion-not-working
- name: Run the equivalent of "pacman -Sy" as a separate step
  community.general.pacman:
    update_cache: true

- name: pacman - Update listing and install packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ pacman_installed_packages }}"
  tags: ['pacman', 'workstation-arch', 'package']

#- name: yay - Update listing and install packages
#  community.general.pacman:
#    name: "{{ item }}"
#    state: present
#    executable: yay
#  loop: "{{ yay_installed_packages }}"
#  tags: ['pacman', 'workstation-arch', 'package']

# pacman settings
# credit to: https://github.com/DoTheEvo/ansible-arch
# settings per: [GUIDE] How to install Arch Linux! https://youtu.be/5y09CR6iCf0?t=818

- name: pacman - enable color
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^#Color$'
    line: 'Color'

- name: pacman - enable ParallelDownloads = 5
  lineinfile:
    path: /etc/pacman.conf
    regexp: '#ParallelDownloads = 5'
    line: 'ParallelDownloads = 5'

- name: pacman - enable multilib
  lineinfile:
    path: /etc/pacman.conf
    regexp: '#[multilib]'
    line: '[multilib]'

- name: pacman - enable multilib
  lineinfile:
    path: /etc/pacman.conf
    regexp: '#Include = /etc/pacman.d/mirrorlist'
    line: 'Include = /etc/pacman.d/mirrorlist'
