# Variables for playbooks

downloads: ~/.ansible-downloads/

# Location of this repository
dotfiles_repo: "git@github.com:justunsix/dotfiles.git"
dotfiles_repo_version: "main"
dotfiles_repo_accept_hostkey: false
dotfiles_repo_local_destination: "~/Code/dotfiles"

dotfiles_home: "~"

# Optional location of dotfile overlay to override or add to existing dotfiles in this repository
dotfiles_overlay_dir: "{{ playbook_dir }}/../dotfiles-overlay"

# User for which set up is being done for
# Override with your user name
target_user: user

dotfiles_directories:
  - "/Users/{{ target_user }}/usr/bin"
  - "/Users/{{ target_user }}/Library/Application Support/nushell"
  # Custom nu config files
  - "/Users/{{ target_user }}/.config/nushell"  
  - "/Users/{{ target_user }}/.config/wezterm"
  - "/Users/{{ target_user }}/.config/helix"

dotfiles_to_be_removed:
  - "/Users/{{ target_user }}/.emacs"
  - "/Users/{{ target_user }}/.emacs.d"

dotfiles_files:
  - usr/bin/common.sh
  - usr/bin/jt-gc.sh
  - usr/bin/jt-gs.sh
  - usr/bin/jt-gt.sh
  - usr/bin/jt-update-all.sh
  - usr/bin/jt-clean-up.sh
  - .config/wezterm/wezterm.lua
  - .config/starship.toml
  - .config/topgrade/topgrade.toml
  - .config/helix/config.toml
  - .config/nushell/config-nix.nu

dotfiles_items_with_custom_destination:
    - { src: ".config/nushell/config.nu", dest: "Library/Application Support/nushell/config.nu" }
    - { src: ".config/nushell/env.nu", dest: "Library/Application Support/nushell/env.nu" }
    - { src: ".config/emacs/setup/minimal.el", dest: ".config/emacs/init.el" }

dotfiles_files_binaries:
  - usr/bin/common.sh
  - usr/bin/jt-gc.sh
  - usr/bin/jt-gs.sh
  - usr/bin/jt-gt.sh
  - usr/bin/jt-update-all.sh
  - usr/bin/jt-clean-up.sh

# Whether to configure certain build items
configure_dotfiles: true
configure_todoandcht: false
configure_mpv: false
configure_dolphin: false
configure_emacs: false

nix_installed_packages:
  # System
  - nixpkgs.topgrade
  # Shell
  - nixpkgs.nushell
  - nixpkgs.starship
  - nixpkgs.zoxide
  - nixpkgs.carapace
  - nixpkgs.atuin
  - nixpkgs.broot
  # Configuration
  - nixpkgs.stow
  # DevOps
  - nixpkgs.helix
  # vagrant: Native extensions take too long to build
  # - nixpkgs.vagrant

homebrew_installed_casks:
  # Web
  - homebrew/cask/firefox
  - homebrew/cask/wezterm
  - homebrew/cask/visual-studio-code
  # - homebrew/cask/emacs
  - homebrew/cask/virtualbox
  - homebrew/cask/vagrant
