# Basic authentication
# Change to same name as Windows user
ansible_user: justi
# Using ask-pass
# ansible_password: Password
ansible_connection: winrm
ansible_winrm_transport: basic
# Use HTTPS port, by default Ansible will use https connection scheme
ansible_winrm_scheme: https
ansible_port: 5986

# Ignore self-signed certificate warnings
ansible_winrm_server_cert_validation: ignore

dotfiles_repo_local_destination: "~/Code/dotfiles"
# Optional location of dotfile overlay to override or add to existing dotfiles in this repository
dotfiles_overlay_dir: "{{ playbook_dir }}/../dotfiles-overlay"

target_user: user

chocolatey_installed_packages:
  ## Package Management
  - chocolatey
  ### Manage terminal using Windows store/winget instead
  ###- microsoft-windows-terminal
  # Security
  - veracrypt
  ### Emacs
  - hunspell.portable
  #### msys2 for org-roam sqlite gcc, replaced by scoop gcc
  #### - msys2

chocolatey_installed_packages_extras:
  ## Games
  - steam
  - ubisoft-connect

scoop_installed_packages:
  ## System
  - btop
  ## Package Management
  - topgrade
  ## File Management
  - git
  - git-credential-manager
  - lazygit
  - bleachbit
  - ccleaner
  - fzf
  - uutils-coreutils
  - eza
  - less
  - bat
  ### fd optional for Emacs and nvim frameworks
  - fd
  ### rg optional for Emacs and nvim frameworks
  - ripgrep
  - duf
  - bottom
  - everything
  - kondo
  - broot
  ## To differentiate from dolphin emulator
  - extras/dolphin
  ### yazi file manager and supporting programs
  - yazi
  #### yazi optional dependencies
  - unar
  - jq
  - poppler
  # Media
  - upscayl
  ## Web
  - firefox
  ## Fonts
  - JetBrains-Mono
  ### RSS
  - fluent-reader
  ## OCR
  - capture2text
  ## Shell / Terminal
  - pwsh
  - zoxide
  - gsudo
  - mprocs
  - dog
  - wezterm
  - cygwin
  - carapace-bin
  - nu
  ### protobuf required for cargo binstall atuin
  - protobuf
  ### Prompt
  - starship
  ## Office, Productivity
  - libreoffice
  - peazip
  - plantuml
  - draw.io
  - anki
  # - calibre
  - autohotkey
  ## Media
  - vlc
  - mpv
  ## Security
  - keepassxc
  ## DevOps
  - vscode
  # - pycharm
  - helix
  - nodejs
  ### Languages
  - make
  #### Python
  ##### Required for Ansible management
  - python
  ##### Virtual environments
  - miniconda3
  # Replace pipx with uv
  # - pipx
  ##### Python package, project, tool manager
  - uv
  #### Java
  - temurin-lts-jdk
  - maven
  #### VS Code Polyglot literate programming
  - dotnet-sdk
  ### Emacs and Supporting Programs
  - emacs
  - pandoc
  #### Emacs Doom Framework
  - llvm
  #### For use with Emacs diff
  - diffutils
  #### Shellcheck used by Emacs Flymake for shell scripts by default - Emacs 29.1
  - shellcheck
  #### Used by org-download for clipboard pasting to org
  - imagemagick
  ### Neovim and Supporting Programs
  - neovim
  #### for telescope fzf native
  - cmake
  #### Astrovim dependencies
  # - win32yank
  # - tree-sitter
  #### For Neovim and Emacs org-roam SQLite
  - gcc

scoop_installed_packages_extras:
  ## Communications
  - discord

# Default dictionary directories installed by chocolately
libre_office_dir: "C:\\Users\\{{ target_user }}\\scoop\\apps\\libreoffice\\current\\LibreOffice"
hunspell_dict_en_dir: "{{ libre_office_dir }}\\share\\extensions\\dict-en"
hunspell_dict_fr_dir: "{{ libre_office_dir }}\\share\\extensions\\dict-fr"

dotfiles_directories:
  - "{{ ansible_env.USERPROFILE }}/.config"
  - "{{ ansible_env.USERPROFILE }}/usr/bin"
  - "{{ ansible_env.USERPROFILE }}/AppData/Local/nvim"
  - "{{ ansible_env.USERPROFILE }}/AppData/Roaming/topgrade"
  - "{{ ansible_env.USERPROFILE }}/.config/emacs"
  - "{{ ansible_env.USERPROFILE }}/.config/doom"
  - "{{ ansible_env.USERPROFILE }}/.config/wezterm"
  - "{{ ansible_env.USERPROFILE }}/.config/todotxt-cli"
  - "{{ ansible_env.USERPROFILE }}/.config/fish"
  - "{{ ansible_env.USERPROFILE }}/AppData/Roaming/helix"
  - "{{ ansible_env.USERPROFILE }}/AppData/Roaming/dystroy/broot/config"
  - "{{ ansible_env.USERPROFILE }}/AppData/Roaming/navi"
  - "C:/Hunspell"

dotfiles_to_be_removed:
  - "{{ ansible_env.USERPROFILE }}/AppData/Local/topgrade.toml"
  - "{{ ansible_env.USERPROFILE }}/.emacs"
  - "{{ ansible_env.USERPROFILE }}/.emacs.d"
  - "{{ ansible_env.USERPROFILE }}/.emacs.d"
  - "{{ ansible_env.USERPROFILE }}/Documents/PowerShell/profile.ps1"
  - "{{ ansible_env.USERPROFILE }}/Documents/WindowsPowerShell/profile.ps1"

dotfiles_items:
  # Reserve for Doom Emacs install
  # - { src: "{{ dotfiles_repo_local_destination }}/.config/emacs/", dest: "{{ ansible_env.USERPROFILE }}/.config/emacs" }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/doom/",
      dest: "{{ ansible_env.USERPROFILE }}/.config/doom",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/usr/bin-windows/",
      dest: "{{ ansible_env.USERPROFILE }}/usr/bin",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}//other/Hunspell/",
      dest: "C:/Hunspell",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/nvim/",
      dest: "{{ ansible_env.USERPROFILE }}/AppData/Local/nvim",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/mpv/",
      dest: "{{ ansible_env.USERPROFILE }}/scoop/apps/mpv/current/portable_config",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/topgrade/",
      dest: "{{ ansible_env.USERPROFILE }}/AppData/Roaming/topgrade",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/nushell/",
      dest: "{{ ansible_env.USERPROFILE }}/AppData/Roaming/nushell",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/navi/",
      dest: "{{ ansible_env.USERPROFILE }}/AppData/Roaming/navi",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/starship.toml",
      dest: "{{ ansible_env.USERPROFILE }}/.config/starship.toml",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/gfold.toml",
      dest: "{{ ansible_env.USERPROFILE }}/.config/gfold.toml",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/kdeglobals",
      dest: "{{ ansible_env.USERPROFILE }}/.config/kdeglobals",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/dolphinrc",
      dest: "{{ ansible_env.USERPROFILE }}/.config/dolphinrc",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/vlc/",
      dest: "{{ ansible_env.USERPROFILE }}/scoop/apps/vlc/current/portable_config",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/wezterm/",
      dest: "{{ ansible_env.USERPROFILE }}/.config/wezterm",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/todotxt-cli/",
      dest: "{{ ansible_env.USERPROFILE }}/.config/todotxt-cli",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/fish/",
      dest: "{{ ansible_env.USERPROFILE }}/.config/fish",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/helix/",
      dest: "{{ ansible_env.USERPROFILE }}/AppData/Roaming/helix",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.config/broot/",
      dest: "{{ ansible_env.USERPROFILE }}/AppData/Roaming/dystroy/broot/config",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/.gitconfig",
      dest: "{{ ansible_env.USERPROFILE }}/.gitconfig",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/other/WindowsPowerShell/Microsoft.PowerShell_profile.ps1",
      dest: "{{ ansible_env.USERPROFILE }}/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1",
    }
  - {
      src: "{{ dotfiles_repo_local_destination }}/other/PowerShell/Microsoft.PowerShell_profile.ps1",
      dest: "{{ ansible_env.USERPROFILE }}/Documents/PowerShell/Microsoft.PowerShell_profile.ps1",
    }

hunspell_dictionaries:
  - { src: "{{ hunspell_dict_en_dir }}\\en_AU.aff", dest: "C:/Hunspell" }
  - { src: "{{ hunspell_dict_en_dir }}\\en_AU.dic", dest: "C:/Hunspell" }
  - { src: "{{ hunspell_dict_en_dir }}\\en_CA.aff", dest: "C:/Hunspell" }
  - { src: "{{ hunspell_dict_en_dir }}\\en_CA.dic", dest: "C:/Hunspell" }
  - { src: "{{ hunspell_dict_en_dir }}\\en_GB.aff", dest: "C:/Hunspell" }
  - { src: "{{ hunspell_dict_en_dir }}\\en_GB.dic", dest: "C:/Hunspell" }
  - { src: "{{ hunspell_dict_en_dir }}\\en_US.aff", dest: "C:/Hunspell" }
  - { src: "{{ hunspell_dict_en_dir }}\\en_US.dic", dest: "C:/Hunspell" }
  - { src: "{{ hunspell_dict_en_dir }}\\en_ZA.aff", dest: "C:/Hunspell" }
  - { src: "{{ hunspell_dict_en_dir }}\\en_ZA.dic", dest: "C:/Hunspell" }
  - { src: "{{ hunspell_dict_fr_dir }}\\fr.aff", dest: "C:/Hunspell" }
  - { src: "{{ hunspell_dict_fr_dir }}\\fr.dic", dest: "C:/Hunspell" }

environment_variables:
  # Windows Emacs Configuration
  # Assume following are installed by system tasks for Emacs:
  # - Fonts
  # - ripgrep, hunspell, pandoc
  # Set home to "C:\Users\justi\"
  - { name: "HOME", value: "{{ ansible_env.USERPROFILE }}" }
  - { name: "EDITOR", value: "nvim" }
