# Basic authentication
# Change to same name as Windows user
ansible_user: justi
# Using ask-pass
# ansible_password: Password
ansible_connection: winrm
ansible_winrm_transport: basic
# Use HTTPS port, by default Ansible will use https connection scheme
ansible_winrm_scheme: https
ansible_port: 5986

# Ignore self-signed certificate warnings
ansible_winrm_server_cert_validation: ignore

dotfiles_repo_local_destination: "~/Code/dotfiles"
# Optional location of dotfile overlay to override or add to existing dotfiles in this repository
dotfiles_overlay_dir: "{{ playbook_dir }}/../dotfiles-overlay"

target_user: user

target_user_home_dir: "C:/Users/{{ target_user }}"

chocolatey_installed_packages:
  ## Package Management
  - chocolatey
  ### Manage terminal using Windows store/winget instead
  ###- microsoft-windows-terminal
  ### Python required for Ansible management
  - python3
  # - googlechrome
  ## Fonts
  - jetbrainsmono
  # Security
  - veracrypt
  ### Emacs
  - hunspell.portable
  #### msys2 for org-roam sqlite gcc, replaced by scoop gcc
  #### - msys2

chocolatey_installed_packages_extras:
  ## Games
  - steam
  - ubisoft-connect

scoop_installed_packages:
  ## Package Management
  - topgrade
  ## File Management
  - git
  - git-credential-manager
  - gitui
  - bleachbit
  - ccleaner
  - fzf
  - fd
  - duf
  - bottom
  - everything
  - kondo
  # Media
  - krita
  - upscayl
  - obs-studio
  ## Web
  - firefox
  ### RSS
  - fluent-reader
  ## OCR
  - capture2text
  ## Shell / Terminal
  - zoxide
  - gsudo
  - mprocs
  - dog
  - wezterm
  - cygwin
  ### Prompt
  - starship
  ## Office, Productivity
  - libreoffice
  - peazip
  - plantuml
  - draw.io
  - anki
  - calibre
  - autohotkey  
  ## Media
  - vlc
  - mpv
  ## Security
  - keepassxc
  ## DevOps
  - vscode
  - pycharm
  - helix
  - nodejs
  - make
  ### Python
  - miniconda3
  ### Java
  - temurin-lts-jdk
  - maven
  ### Emacs
  - emacs
  - ripgrep
  - pandoc
  #### Shellcheck used by Emacs Flymake for shell scripts by default - Emacs 29.1
  - shellcheck
  #### Used by org-download for clipboard pasting to org
  - imagemagick
  ### Neovim
  - neovim
  #### for telescope fzf native
  - cmake
  #### For Neovim and Emacs org-roam SQLite
  - gcc
  ### Polyglot literate programming
  - dotnet-sdk

scoop_installed_packages_extras:
  ## Communications
  - discord

# Default dictionary directories installed by chocolately
libre_office_dir: "C:\\Users\\{{ target_user }}\\scoop\\apps\\libreoffice\\current\\LibreOffice"
hunspell_dict_en_dir: "{{ libre_office_dir }}\\share\\extensions\\dict-en"
hunspell_dict_fr_dir: "{{ libre_office_dir }}\\share\\extensions\\dict-fr"

dotfiles_directories:
    - "{{ target_user_home_dir }}/.config"
    - "{{ target_user_home_dir }}/usr/bin"
    - "{{ target_user_home_dir }}/AppData/Local/nvim"
    - "{{ target_user_home_dir }}/AppData/Roaming/topgrade"
    - "{{ target_user_home_dir }}/.config/emacs"
    - "{{ target_user_home_dir }}/.config/wezterm"
    - "{{ target_user_home_dir }}/.config/todotxt-cli"
    - "{{ target_user_home_dir }}/.config/fish"
    - "{{ target_user_home_dir }}/.config/helix"
    - "C:/Hunspell"

dotfiles_to_be_removed:
    - "{{ target_user_home_dir }}/AppData/Local/topgrade.toml"
    - "{{ target_user_home_dir }}/.emacs"
    - "{{ target_user_home_dir }}/.emacs.d"

dotfiles_items:
    - { src: "{{ dotfiles_repo_local_destination }}/.config/emacs/", dest: "{{ target_user_home_dir }}/.config/emacs" }
    - { src: "{{ dotfiles_repo_local_destination }}/usr/bin-windows/", dest: "{{ target_user_home_dir }}/usr/bin" }
    - { src: "{{ dotfiles_repo_local_destination }}//other/Hunspell/", dest: 'C:/Hunspell' }
    - { src: "{{ dotfiles_repo_local_destination }}/.config/nvim/", dest: "{{ target_user_home_dir }}/AppData/Local/nvim" }
    - { src: "{{ dotfiles_repo_local_destination }}/.config/mpv/", dest: "{{ target_user_home_dir }}/scoop/apps/mpv/current/portable_config" }
    - { src: "{{ dotfiles_repo_local_destination }}/.config/topgrade/", dest: "{{ target_user_home_dir }}/AppData/Roaming/topgrade" }
    - { src: "{{ dotfiles_repo_local_destination }}/.config/nushell/", dest: "{{ target_user_home_dir }}/AppData/Roaming/nushell" }
    - { src: "{{ dotfiles_repo_local_destination }}/.config/starship.toml", dest: "{{ target_user_home_dir }}/.config/starship.toml" }
    - { src: "{{ dotfiles_repo_local_destination }}/.config/vlc/", dest: "{{ target_user_home_dir }}/scoop/apps/vlc/current/portable_config" }
    - { src: "{{ dotfiles_repo_local_destination }}/.config/wezterm/", dest: "{{ target_user_home_dir }}/.config/wezterm" }
    - { src: "{{ dotfiles_repo_local_destination }}/.config/todotxt-cli/", dest: "{{ target_user_home_dir }}/.config/todotxt-cli" }
    - { src: "{{ dotfiles_repo_local_destination }}/.config/fish/", dest: "{{ target_user_home_dir }}/.config/fish" }
    - { src: "{{ dotfiles_repo_local_destination }}/.config/helix/", dest: "{{ target_user_home_dir }}/.config/helix" }
    - { src: "{{ dotfiles_repo_local_destination }}/.gitconfig", dest: "{{ target_user_home_dir }}/.gitconfig" }
    - { src: "{{ dotfiles_repo_local_destination }}/other/WindowsPowerShell/Microsoft.PowerShell_profile.ps1", dest: 'C:/Users/{{ target_user }}/OneDrive/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1' }
    - { src: "{{ dotfiles_repo_local_destination }}/other/PowerShell/Microsoft.PowerShell_profile.ps1", dest: 'C:/Users/{{ target_user }}/OneDrive/Documents/PowerShell/Microsoft.PowerShell_profile.ps1' }

hunspell_dictionaries:
  - { src: "{{ hunspell_dict_en_dir }}\\en_AU.aff", dest: 'C:/Hunspell' }
  - { src: "{{ hunspell_dict_en_dir }}\\en_AU.dic", dest: 'C:/Hunspell' }
  - { src: "{{ hunspell_dict_en_dir }}\\en_CA.aff", dest: 'C:/Hunspell' }
  - { src: "{{ hunspell_dict_en_dir }}\\en_CA.dic", dest: 'C:/Hunspell' }
  - { src: "{{ hunspell_dict_en_dir }}\\en_GB.aff", dest: 'C:/Hunspell' }
  - { src: "{{ hunspell_dict_en_dir }}\\en_GB.dic", dest: 'C:/Hunspell' }
  - { src: "{{ hunspell_dict_en_dir }}\\en_US.aff", dest: 'C:/Hunspell' }
  - { src: "{{ hunspell_dict_en_dir }}\\en_US.dic", dest: 'C:/Hunspell' }
  - { src: "{{ hunspell_dict_en_dir }}\\en_ZA.aff", dest: 'C:/Hunspell' }
  - { src: "{{ hunspell_dict_en_dir }}\\en_ZA.dic", dest: 'C:/Hunspell' }
  - { src: "{{ hunspell_dict_fr_dir }}\\fr.aff", dest: 'C:/Hunspell' }
  - { src: "{{ hunspell_dict_fr_dir }}\\fr.dic", dest: 'C:/Hunspell' }

environment_variables:
  # Windows Emacs Configuration
  # Assume following are installed by system tasks for Emacs:
  # - Fonts
  # - ripgrep, hunspell, pandoc
  # Set home to "C:\Users\justi\"
  - { name: "HOME", value: "{{ ansible_env.USERPROFILE }}" }
  - { name: "EDITOR", value: "nvim" }