# Basic authentication
# Change to same name as Windows user
ansible_user: justi
# Using ask-pass
# ansible_password: Password
ansible_connection: winrm
ansible_winrm_transport: basic
# Use HTTPS port, by default Ansible will use https connection scheme
ansible_winrm_scheme: https
ansible_port: 5986

# Ignore self-signed certificate warnings
ansible_winrm_server_cert_validation: ignore

dotfiles_repo_local_destination: "~/Code/dotfiles"
# Optional location of dotfile overlay to override or add to existing dotfiles in this repository
dotfiles_overlay_dir: "{{ playbook_dir }}/../dotfiles-overlay"

target_user: user

target_user_home_dir: "C:/Users/{{ target_user }}"

chocolatey_installed_packages:
  ## Package Management
  - chocolatey
  ## System
  - autohotkey  
  ### Manage terminal using Windows store/winget instead
  ###- microsoft-windows-terminal
  - ccleaner
  ## File Management
  - git
  - git-credential-manager-for-windows
  ### Python required for Ansible management
  - python3
  # - googlechrome
  ## Fonts
  - jetbrainsmono
  # Security
  - veracrypt
  - keepassxc
  ## DevOps
  - cygwin
  - vscode
  ### Emacs
  - emacs
  - ripgrep
  - hunspell.portable
  - pandoc
  - nodejs

# For information, variable not used
chocolatey_installed_packages-migrated-to-scoop:  
  ## Web
  - firefox
  ## OCR
  - capture2text
  ## Shell
  - zoxide  
  ## Office, Productivity
  - libreoffice-fresh
  - peazip
  - plantuml
  - drawio
  ## File Management
  - fzf
  - fd
  ## Media
  - vlc
  - mpv  

chocolatey_installed_packages_work:
  ## VM
  - virtualbox
  ## Graphics and Media
  - inkscape
  - gimp
  - obs-studio
  ## DevOps
  - azure-cli
  - python
  - maven
  - mremoteng
  - terraform
  ## Documents
  - pdfxchangeeditor

scoop_installed_packages_work:
  ## Graphics and Media
  - inkscape
  - gimp

chocolatey_installed_packages_extras:
  ## Communications
  - discord
  ## Games
  - steam
  - ubisoft-connect

scoop_installed_packages:
  # Media
  - krita
  - upscayl
  ## Web
  - firefox
  ## OCR
  - capture2text
  ## Shell
  - zoxide
  ### Prompt
  - starship  
  ## Office, Productivity
  - libreoffice
  - peazip
  - plantuml
  - draw.io
  ## File Management
  - fzf
  - fd
  ## Media
  - vlc
  - mpv  

# Default dictionary directories installed by chocolately
libre_office_dir: "C:\\Users\\{{ target_user }}\\scoop\\apps\\libreoffice\\current\\LibreOffice"
hunspell_dict_en_dir: "{{ libre_office_dir }}\\share\\extensions\\dict-en"
hunspell_dict_fr_dir: "{{ libre_office_dir }}\\share\\extensions\\dict-fr"

dotfiles_items:
    - { src: "{{ dotfiles_repo_local_destination }}/usr/bin-windows/", dest: "C:/Users/{{ target_user }}/usr/bin" }
    - { src: "{{ dotfiles_repo_local_destination }}//other/Hunspell/", dest: 'C:/Hunspell' }

hunspell_dictionaries:
    - { src: "{{ hunspell_dict_en_dir }}\\en_AU.aff", dest: 'C:/Hunspell' }
    - { src: "{{ hunspell_dict_en_dir }}\\en_AU.dic", dest: 'C:/Hunspell' }
    - { src: "{{ hunspell_dict_en_dir }}\\en_CA.aff", dest: 'C:/Hunspell' }
    - { src: "{{ hunspell_dict_en_dir }}\\en_CA.dic", dest: 'C:/Hunspell' }
    - { src: "{{ hunspell_dict_en_dir }}\\en_GB.aff", dest: 'C:/Hunspell' }
    - { src: "{{ hunspell_dict_en_dir }}\\en_GB.dic", dest: 'C:/Hunspell' }
    - { src: "{{ hunspell_dict_en_dir }}\\en_US.aff", dest: 'C:/Hunspell' }
    - { src: "{{ hunspell_dict_en_dir }}\\en_US.dic", dest: 'C:/Hunspell' }
    - { src: "{{ hunspell_dict_en_dir }}\\en_ZA.aff", dest: 'C:/Hunspell' }
    - { src: "{{ hunspell_dict_en_dir }}\\en_ZA.dic", dest: 'C:/Hunspell' }
    - { src: "{{ hunspell_dict_fr_dir }}\\fr.aff", dest: 'C:/Hunspell' }
    - { src: "{{ hunspell_dict_fr_dir }}\\fr.dic", dest: 'C:/Hunspell' }
