# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-'SCRIPT'

# Update system
pacman --noconfirm -Syyu
# Install Ansible 
# Install convenience software
pacman --noconfirm -S fish starship ansible python-pywinrm zoxide make
# Track VM creation time                      
date > /etc/vagrant_provisioned_at
# Add cd to dotfiles-playbook and fish start to .bashrc
echo "cd /home/vagrant/Code/dotfiles-playbook" >> /home/vagrant/.bashrc
echo "fish" >> /home/vagrant/.bashrc
# Install Ansible requirements
cd /home/vagrant/Code/dotfiles-playbook/
export ANSIBLE_CONFIG=ansible.cfg
ansible-galaxy collection install -r requirements-windows.yml

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.provider "virtualbox" do |v|
    # https://www.vagrantup.com/docs/providers/virtualbox/configuration
    v.name = "Archlinux_dotfiles_manager"
    v.linked_clone = true
  end
  
  ############################################################
  # Copy some host files to configure VM like the host
  ############################################################

  # Copy your Starsip config file for prompt
  if File.exists?(File.expand_path("#{ENV['HOME']}/.config/starship.toml"))
    config.vm.provision "file", source: "#{ENV['HOME']}/.config/starship.toml", destination: ".config/starship.toml"
  end

  # Copy your nushell config (uses Windows locations)
  # if nushell directory exists, copy its contents to the VM at ~/.config/nushell
  if File.directory?(File.expand_path("#{ENV['HOME']}/.config/fish/config.fish"))
    config.vm.provision "file", source: "#{ENV['HOME']}/.config/fish/config.fish", destination: ".config/fish/config.fish"
  end

  ############################################################
  # Mount repositories from the host
  ############################################################

  # If exists, mount ~/Code from Host to /home/vagrant/Code in VM
  if File.directory?(File.expand_path("#{ENV['HOME']}/Code"))
    config.vm.synced_folder "#{ENV['HOME']}/Code", "/home/vagrant/Code"
  end

  config.vm.provision "shell", inline: $script

end