# See https://docs.ansible.com/ansible/latest/collections/community/general/homebrew_module.html

# Update and upgrade all apt installed packages
- name: homebrew - Update and upgrade all installed packages
  community.general.homebrew:
    name: homebrew/cask/firefox
    state: latest
  tags: ['homebrew', 'workstation-macos', 'package']

# Update homebrew and upgrade all packages
- community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  tags: ['homebrew', 'workstation-macos', 'package']